services:
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/usr/src/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    restart: unless-stopped
