services:
  backend:
    build:
      context: ./backend
    environment:
      - FLASK_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://api.example.com # Change to your production API URL
    restart: always

  # Optional reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   depends_on:
  #     - frontend
  #     - backend
  #   restart: always
